routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;

/*
 *** PUBLIC WEBSITE (views):
 */
Route::get('/', 'PublicViewController@showHome')->name('home');
Route::post('/lead', 'Message\LeadController@store')->name('lead.store');

Auth::routes();

Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);

/*
 *** USERS PANEL (views):
 */
Route::prefix('user')->group(function () {
    Route::name('user.')->group(function () {

        Route::prefix('profile')->group(function () {
            Route::get('/', 'UserViewController@profile')->name('profile');

            Route::name('profile.')->group(function () {
                Route::get('edit', 'UserViewController@editProfile')->name('edit');
                Route::get('/password/change', 'UserViewController@showChangePassword')->name('password.change');

                Route::prefix('address')->group(function () {
                    Route::name('address.')->group(function () {
                        Route::get('/create', 'UserViewController@createAddress')->name('new');
                        Route::get('{address}', 'UserViewController@showAddress')->name('detail');
                        Route::get('{address}/edit', 'UserViewController@editAddress')->name('edit');
                    });
                });
            });
        });

        Route::prefix('address')->group(function () {
            Route::name('address.')->group(function () {
                Route::get('{address}', 'UserViewController@showAddress')->name('detail');
                Route::get('{address}/edit', 'UserViewController@editAddress')->name('edit');
            });
        });

        Route::get('appointments', 'UserViewController@appointments')->name('appointments');

        Route::prefix('mailbox')->group(function () {
            Route::get('/', 'UserViewController@showInbox')->name('inbox');

            Route::name('mailbox.')->group(function () {
                Route::get('create', 'UserViewController@createMessage')->name('new');
                Route::get('history', 'UserViewController@showHistory')->name('history');
                Route::get('{message}', 'UserViewController@showMessage')->name('detail');
            });
        });
    });
});

/*
 *** ADMIN PANEL (views):
 */
Route::prefix('admin')->group(function () {

    Route::name('admin.')->group(function () {
        Route::get('/', 'AdminViewController@showDashboard')->name('dashboard');

        Route::prefix('profile')->group(function () {
            Route::get('/', 'AdminViewController@showProfile')->name('profile');

            Route::name('profile.')->group(function () {
                Route::get('edit', 'AdminViewController@editProfile')->name('edit');
                Route::get('/password/change', 'AdminViewController@showChangePassword')->name('password.change');
                Route::get('/password/changed', 'AdminViewController@showChangePassword')->name('password.changed');

                Route::prefix('address')->group(function () {
                    Route::name('address.')->group(function () {
                        Route::get('/create', 'AdminViewController@createAddress')->name('new');
                        Route::get('{address}', 'AdminViewController@showAddress')->name('detail');
                        Route::get('{address}/edit', 'AdminViewController@editAddress')->name('edit');
                    });
                });
            });
        });

        Route::prefix('addresses')->group(function () {
            Route::get('/', 'AdminViewController@showAddresses')->name('addresses');
        });

        Route::prefix('address')->group(function () {
            Route::name('address.')->group(function () {
                Route::get('{address}', 'AdminViewController@showAddress')->name('detail');
                Route::get('{address}/edit', 'AdminViewController@editAddress')->name('edit');
            });
        });



        Route::prefix('mailbox')->group(function () {
            Route::get('/', 'AdminViewController@showInbox')->name('inbox');

            Route::name('mailbox.')->group(function () {
                Route::get('create', 'AdminViewController@createMessage')->name('new');
                Route::get('history', 'AdminViewController@showHistory')->name('history');
                Route::get('{message}', 'AdminViewController@showMessage')->name('detail');
            });
        });

        Route::prefix('appointments')->group(function () {
            Route::get('/', 'AdminViewController@showAppointmentsCalendar')->name('appointments');

            Route::name('appointments.')->group(function () {
                Route::get('pending', 'AdminViewController@showAppointmentsPending')->name('pending');
                Route::get('history', 'AdminViewController@showAppointmentsHistory')->name('history');
            });
        });

        Route::prefix('appointment')->group(function () {
            Route::name('appointment.')->group(function () {
                Route::get('create', 'AdminViewController@createAppointment')->name('new');
                Route::get('{appointment}', 'AdminViewController@showAppointment')->name('detail');
                Route::get('{appointment}/edit', 'AdminViewController@editAppointment')->name('edit');
            });
        });

        Route::prefix('users')->group(function () {
            Route::get('/', 'AdminViewController@showUsers')->name('users');
        });

        Route::prefix('user')->group(function () {
            Route::name('user.')->group(function () {
                Route::get('{user}', 'AdminViewController@showProfile')->name('detail');
                Route::get('{user}/edit', 'AdminViewController@editProfile')->name('edit');
                Route::get('{user}/role/edit', 'AdminViewController@showChangeRole')->name('role.edit');
                Route::get('{user}/address/new', 'AdminViewController@createAddress')->name('address.new');
                Route::get('address/{address}', 'AdminViewController@showAddress')->name('address.detail');
                Route::get('address/{address}/edit', 'AdminViewController@editAddress')->name('address.edit');
            });
        });
    });

});



/*
 *** MODELS RESOURCE CONTROLLERS:
 */
Route::resource('address', 'Address\AddressController')->except('index', 'show' , 'create', 'edit');
Route::resource('message', 'Message\MessageController')->except('index', 'show' , 'create', 'edit');
Route::resource('users', 'User\UsersController')->except('index', 'create', 'show', 'edit', 'store');
Route::resource('appointment', 'Appointment\AppointmentController')->except('index', 'show' , 'create', 'edit');




Route::put('users/{user}/pass', 'User\UsersController@changePassword')->name('users.change.password');
Route::put('users/{user}/role', 'User\UsersController@changeRole')->name('users.change.role');
Route::get('users/{user}', 'User\UsersController@activate')->name('users.activate');
Route::get('/message/{recipient}/unread', 'Message\MessageController@updateIsUnread')->name('message.update.unread');
Route::get('/message/{recipient}/isread', 'Message\MessageController@updateIsRead')->name('message.update.read');
Route::delete('/message/{message}/{recipient}', 'Message\MessageController@destroyRecipient')->name('message.destroy.recipient');

resources/views/admin_panel/nav/nav-bar.blade.php
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{{ url('/') }}">
        {{ config('app.name', 'Laravel') }}
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Right Side Of Navbar -->
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav ml-auto">


            <!-- Authentication Links -->
            @guest
                <li><a class="nav-link" href="{{ route('login') }}">{{ __('Inloggen') }}</a></li>
                <li><a class="nav-link" href="{{ route('register') }}">{{ __('Registreren') }}</a></li>
            @else
                <li class="nav-item dropdown">
                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        {{ Auth::user()->full_name }} <span class="caret"></span>
                    </a>

                    <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="right: 0; left:auto;">
                        <a class="dropdown-item" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                            {{ __('Uitloggen') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                </li>
            @endguest
        </ul>
    </div>

</nav>

resources/views/admin_panel/nav/side-bar.blade.php
<nav class="sidebar">
    <!-- Sidebar Links -->
    <ul class="list-unstyled">
        <li class="{{ Request::is('admin') ? 'active' : '' }}">
            <a href="{{route('admin.dashboard')}}">
                <i class="fas fa-fw fa-chart-line"></i>
                <span class="label">Dashboard</span>
            </a>
        </li>
        <li class="{{ (Request::is('admin/profile/') || Request::is('admin/profile') || Request::is('admin/profile/*') ? 'active' : '') }}">
            <a href="{{route('admin.profile')}}">
                <i class="fas fa-fw fa-user-circle"></i>
                <span class="label">Profiel</span>
            </a>
        </li>
        <li class="{{ (Request::is('admin/mailbox/') || Request::is('admin/mailbox') || Request::is('admin/mailbox/*') ? 'active' : '') }}">
            <a href="#messagesSubMenu" data-toggle="collapse" aria-expanded="{{ (Request::is('admin/mailbox/') || Request::is('admin/mailbox') || Request::is('admin/mailbox/*') ? 'true' : 'false') }}">
                <i class="fas fa-fw fa-envelope"></i>
                <span class="label">Berichten</span>
            </a>
            <ul class="{{ (Request::is('admin/mailbox/') || Request::is('admin/mailbox') || Request::is('admin/mailbox/*') ? 'show' : '') }} collapse list-unstyled" id="messagesSubMenu">
                <li><a href="{{ route('admin.mailbox.new') }}">Nieuw</a></li>
                <li><a href="{{ route('admin.inbox') }}">Inbox</a></li>
                <li><a href="{{ route('admin.mailbox.history') }}">Verzonden</a></li>
            </ul>
        </li>
        <li class="{{ (Request::is('admin/addresses/') || Request::is('admin/addresses') || Request::is('admin/addresses/*') || Request::is('admin/address/') || Request::is('admin/address') || Request::is('admin/address/*') ? 'active' : '') }}">
            <a href="{{route('admin.addresses')}}">
                <i class="fas fa-fw fa-road"></i>
                <span class="label">Adressen</span>
            </a>
        </li>
    @if(Auth::user()->hasAnyRole(['editor','admin']))
        <li class="{{ (Request::is('admin/appointment/') || Request::is('admin/appointment') || Request::is('admin/appointment/*') || Request::is('admin/appointments/') || Request::is('admin/appointments')|| Request::is('admin/appointments/*') ? 'active' : '') }}">
            <a href="#appointmentsSubMenu" data-toggle="collapse" aria-expanded="{{ (Request::is('admin/appointment/') || Request::is('admin/appointment') || Request::is('admin/appointment/*') || Request::is('admin/appointments/') || Request::is('admin/appointments')|| Request::is('admin/appointments/*') ? 'true' : 'false') }}">
                <i class="fas fa-fw fa-calendar-check"></i>
                <span class="label">Boekingen</span>
            </a>
            <ul class="{{ (Request::is('admin/appointment/') || Request::is('admin/appointment') || Request::is('admin/appointment/*') || Request::is('admin/appointments/') || Request::is('admin/appointments')|| Request::is('admin/appointments/*') ? 'show' : '') }} collapse list-unstyled" id="appointmentsSubMenu">
                <li><a href="{{ route('admin.appointments') }}">Kalender</a></li>
                <li><a href="{{ route('admin.appointments.pending') }}">In Afwachting</a></li>
                <li><a href="{{ route('admin.appointments.history') }}">Geschiedenis</a></li>
            </ul>
        </li>
    @endif
    @if(Auth::user()->hasAnyRole(['admin']))
        <li class="{{ (Request::is('admin/user/') || Request::is('admin/user') || Request::is('admin/user/*') || Request::is('admin/users/') || Request::is('admin/users') || Request::is('admin/users/*') ? 'active' : ' ') }}">
            <a href="{{ route('admin.users') }}">
                <i class="fas fa-fw fa-users"></i>
                <span class="label">Gebruikers</span>
            </a>
        </li>
    @endif
    </ul>

    <ul class="list-unstyled bottom">
        <li>
            <a class="sidebarCollapse">
                <i class="hamburger">
                    <span></span>
                    <span></span>
                    <span></span>
                </i>
                <span class="label">Menu Verbergen</span>
            </a>
        </li>
    </ul>
</nav>