routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;

/*
 *** PUBLIC WEBSITE (views):
 */
Route::get('/', 'PublicViewController@showHome')->name('home');
Route::post('/lead', 'Message\LeadController@store')->name('lead.store');

Auth::routes();

Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);

/*
 *** USERS PANEL (views):
 */
Route::prefix('user')->group(function () {
    Route::name('user.')->group(function () {

        Route::prefix('profile')->group(function () {
            Route::get('/', 'UserViewController@profile')->name('profile');

            Route::name('profile.')->group(function () {
                Route::get('edit', 'UserViewController@editProfile')->name('edit');
                Route::get('/password/change', 'UserViewController@showChangePassword')->name('password.change');

                Route::prefix('address')->group(function () {
                    Route::name('address.')->group(function () {
                        Route::get('/create', 'UserViewController@createAddress')->name('new');
                        Route::get('{address}', 'UserViewController@showAddress')->name('detail');
                        Route::get('{address}/edit', 'UserViewController@editAddress')->name('edit');
                    });
                });
            });
        });

        Route::prefix('address')->group(function () {
            Route::name('address.')->group(function () {
                Route::get('{address}', 'UserViewController@showAddress')->name('detail');
                Route::get('{address}/edit', 'UserViewController@editAddress')->name('edit');
            });
        });

        Route::get('appointments', 'UserViewController@appointments')->name('appointments');

        Route::prefix('mailbox')->group(function () {
            Route::get('/', 'UserViewController@showInbox')->name('inbox');

            Route::name('mailbox.')->group(function () {
                Route::get('create', 'UserViewController@createMessage')->name('new');
                Route::get('history', 'UserViewController@showHistory')->name('history');
                Route::get('{message}', 'UserViewController@showMessage')->name('detail');
            });
        });
    });
});

/*
 *** ADMIN PANEL (views):
 */
Route::prefix('admin')->group(function () {

    Route::name('admin.')->group(function () {
        Route::get('/', 'AdminViewController@showDashboard')->name('dashboard');

        Route::prefix('profile')->group(function () {
            Route::get('/', 'AdminViewController@showProfile')->name('profile');

            Route::name('profile.')->group(function () {
                Route::get('edit', 'AdminViewController@editProfile')->name('edit');
                Route::get('/password/change', 'AdminViewController@showChangePassword')->name('password.change');
                Route::get('/password/changed', 'AdminViewController@showChangePassword')->name('password.changed');

                Route::prefix('address')->group(function () {
                    Route::name('address.')->group(function () {
                        Route::get('/create', 'AdminViewController@createAddress')->name('new');
                        Route::get('{address}', 'AdminViewController@showAddress')->name('detail');
                        Route::get('{address}/edit', 'AdminViewController@editAddress')->name('edit');
                    });
                });
            });
        });

        Route::prefix('addresses')->group(function () {
            Route::get('/', 'AdminViewController@showAddresses')->name('addresses');
        });

        Route::prefix('address')->group(function () {
            Route::name('address.')->group(function () {
                Route::get('{address}', 'AdminViewController@showAddress')->name('detail');
                Route::get('{address}/edit', 'AdminViewController@editAddress')->name('edit');
            });
        });



        Route::prefix('mailbox')->group(function () {
            Route::get('/', 'AdminViewController@showInbox')->name('inbox');

            Route::name('mailbox.')->group(function () {
                Route::get('create', 'AdminViewController@createMessage')->name('new');
                Route::get('history', 'AdminViewController@showHistory')->name('history');
                Route::get('{message}', 'AdminViewController@showMessage')->name('detail');
            });
        });

        Route::prefix('appointments')->group(function () {
            Route::get('/', 'AdminViewController@showAppointmentsCalendar')->name('appointments');

            Route::name('appointments.')->group(function () {
                Route::get('pending', 'AdminViewController@showAppointmentsPending')->name('pending');
                Route::get('history', 'AdminViewController@showAppointmentsHistory')->name('history');
            });
        });

        Route::prefix('appointment')->group(function () {
            Route::name('appointment.')->group(function () {
                Route::get('create', 'AdminViewController@createAppointment')->name('new');
                Route::get('{appointment}', 'AdminViewController@showAppointment')->name('detail');
                Route::get('{appointment}/edit', 'AdminViewController@editAppointment')->name('edit');
            });
        });

        Route::prefix('users')->group(function () {
            Route::get('/', 'AdminViewController@showUsers')->name('users');
        });

        Route::prefix('user')->group(function () {
            Route::name('user.')->group(function () {
                Route::get('{user}', 'AdminViewController@showProfile')->name('detail');
                Route::get('{user}/edit', 'AdminViewController@editProfile')->name('edit');
                Route::get('{user}/role/edit', 'AdminViewController@showChangeRole')->name('role.edit');
                Route::get('{user}/address/new', 'AdminViewController@createAddress')->name('address.new');
                Route::get('address/{address}', 'AdminViewController@showAddress')->name('address.detail');
                Route::get('address/{address}/edit', 'AdminViewController@editAddress')->name('address.edit');
            });
        });
    });

});



/*
 *** MODELS RESOURCE CONTROLLERS:
 */
Route::resource('address', 'Address\AddressController')->except('index', 'show' , 'create', 'edit');
Route::resource('message', 'Message\MessageController')->except('index', 'show' , 'create', 'edit');
Route::resource('users', 'User\UsersController')->except('index', 'create', 'show', 'edit', 'store');
Route::resource('appointment', 'Appointment\AppointmentController')->except('index', 'show' , 'create', 'edit');




Route::put('users/{user}/pass', 'User\UsersController@changePassword')->name('users.change.password');
Route::put('users/{user}/role', 'User\UsersController@changeRole')->name('users.change.role');
Route::get('users/{user}', 'User\UsersController@activate')->name('users.activate');
Route::get('/message/{recipient}/unread', 'Message\MessageController@updateIsUnread')->name('message.update.unread');
Route::get('/message/{recipient}/isread', 'Message\MessageController@updateIsRead')->name('message.update.read');
Route::delete('/message/{message}/{recipient}', 'Message\MessageController@destroyRecipient')->name('message.destroy.recipient');

resources/views/shared/tables/addresses.blade.php
<table class="table table-sm table-hover">
    <thead>
    <tr>
        <th scope="col" width="200">Gebruiker</th>
        <th scope="col" width="70">Type</th>
        <th scope="col">Adres</th>
        <th scope="col" width="30" class="text-center">#</th>
        <th scope="col" width="50" class="text-center">Verwijderd</th>
    </tr>
    </thead>
    <tbody>
    @foreach($addresses as $address)
        <tr class="clickable-row" data-href="{{ route('admin.address.detail', $address) }}">
            <td>{{ ucfirst($users->where('id', '=', $address->created_by_user_id)->first()->full_name) }}</td>
            <td>{{ ucfirst($address->address_type) }}</td>
            <td>{{ ucfirst($address->line_1) }}</td>
            <td class="text-center">{{ $address->line_2 }}</td>
            <td class="text-center">
                @if($address->is_active === 0)
                    <i class="fas fa-fw fa-check"></i>
                @endif
            </td>
        </tr>
    @endforeach
    </tbody>
</table>

resources/views/shared/tables/addresses_widget.blade.php
<table class="table table-sm table-hover">
    <thead>
    <tr>
        <th scope="col" width="70">Type</th>
        <th scope="col">Adres</th>
        <th scope="col" width="30" class="text-center">#</th>
    </tr>
    </thead>
    <tbody>
    @foreach($user->addresses->where('address_type' ,'!=' , 'Home') as $address)

    @if(Request::is('admin/user/') || Request::is('admin/user') || Request::is('admin/user/*'))
        <tr class='clickable-row' data-href='{{  route('admin.user.address.detail', $address) }}'>
    @elseif(Request::is('admin/profile/') || Request::is('admin/profile') || Request::is('admin/profile/*'))
        <tr class='clickable-row' data-href='{{  route('admin.profile.address.detail', $address->id) }}'>
    @else
        <tr class='clickable-row' data-href='{{  route('user.profile.address.detail', $address->id) }}'>
    @endif()
            <td>{{ $address->address_type }}</td>
            <td>{{ $address->line_1 }}</td>
            <td class="text-center">{{ $address->line_2 }}</td>
        </tr>
    @endforeach
    </tbody>
</table>

resources/views/shared/tables/appointments_users.blade.php
<table class="table table-sm">
    <thead>
    <tr>
        <th scope="col" width="50">#</th>
        <th scope="col" width="200">Status</th>
        <th scope="col">Event Titel</th>
        <th scope="col" width="200">Start Datum</th>
        <th scope="col" width="200">Aantal Shows</th>
    </tr>
    </thead>
    <tbody>
    @foreach($appointments as $appointment)
        <tr>
            <th scope="row">{{ $loop->iteration }}</th>
            <td>{{$appointment->status()->first()->name}}</td>
            <td>{{ $appointment->event_title }}</td>
            <td>{{ $appointment->start_time }}</td>
            <td>{{ $appointment->end_time_exp }}</td>
        </tr>
        @if($loop->iteration < 1)
            <tr>
                <td colspan="5"><p>Geen nieuwe afspraken beschikbaar.</p></td>
            </tr>
        @endif
    @endforeach
    </tbody>
</table>

resources/views/shared/tables/calendar.blade.php
@if($appointments !== null)
<table class="table table-sm">
    <thead>
    <tr>
        <th scope="col" width="50">#</th>
        <th scope="col" width="200">Start Datum</th>
        <th scope="col">Event Titel</th>
        <th scope="col" width="200">Aantal Shows</th>
    </tr>
    </thead>
    <tbody>
    @foreach($appointments as $appointment)
        @if($appointment->status()->first()->name === 'Accepted')
            <tr>
                <th scope="row">{{ $loop->iteration }}</th>
                <td>{{ $appointment->status()->first()->name }}</td>
                <td>{{ $appointment->event_title }}</td>
                <td>{{ $appointment->start_time }}</td>
                <td>{{ $appointment->end_time_exp }}</td>
                <td></td>
            </tr>
        @endif
    @endforeach
    </tbody>
</table>
@else
    <p>Er zijn momenteel geen nieuwe afspraken die goedkeuring vereisen.</p>
@endif

resources/views/shared/tables/cancelled.blade.php
@if($appointments !== null)
    <table class="table table-sm">
        <thead>
        <tr>
            <th scope="col" width="50">#</th>
            <th scope="col" width="200">Status</th>
            <th scope="col">Event Titel</th>
            <th scope="col" width="200">Start Datum</th>
            <th scope="col" width="200">Aantal Shows</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        @foreach($appointments as $appointment)
            @if($appointment->status()->first()->name === 'cancelled')
                <tr>
                    <th scope="row">{{ $loop->iteration }}</th>
                    <td>{{ $appointment->status()->first()->name }}</td>
                    <td>{{ $appointment->event_title }}</td>
                    <td>{{ $appointment->start_time }}</td>
                    <td>{{ $appointment->end_time_exp }}</td>
                    <td></td>
                </tr>
            @endif

            @if($loop->iteration < 1)
                <tr>
                    <td colspan="5"><p>Geen nieuwe afspraken beschikbaar.</p></td>
                </tr>
            @endif
        @endforeach
        </tbody>
    </table>
@else
    <p>Er zijn momenteel geen nieuwe afspraken die goedkeuring vereisen.</p>
@endif

resources/views/shared/tables/history.blade.php
@if($appointments !== null)
<table class="table table-sm">
    <thead>
    <tr>
        <th scope="col" width="50">#</th>
        <th scope="col" width="200">Start Datum</th>
        <th scope="col">Event Titel</th>
        <th scope="col" width="200">Aantal Shows</th>
    </tr>
    </thead>
    <tbody>
    @foreach($appointments as $appointment)
        <tr>
            <th scope="row">{{ $loop->iteration }}</th>
            <td>{{ $appointment->status()->first()->name }}</td>
            <td>{{ $appointment->event_title }}</td>
            <td>{{ $appointment->start_time }}</td>
            <td>{{ $appointment->end_time_exp }}</td>
            <td></td>
        </tr>
    @endforeach
    </tbody>
</table>
@else
    <p>Er zijn momenteel geen nieuwe afspraken die goedkeuring vereisen.</p>
@endif

resources/views/shared/tables/pending.blade.php
@if($appointments !== null)
<table class="table table-sm">
    <thead>
    <tr>
        <th scope="col" width="50">#</th>
        <th scope="col" width="200">Status</th>
        <th scope="col">Event Titel</th>
        <th scope="col" width="200">Start Datum</th>
        <th scope="col" width="200">Aantal Shows</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    @foreach($appointments as $appointment)
        @if($appointment->status()->first()->name === 'Pending')
        <tr>
            <th scope="row">{{ $loop->iteration }}</th>
            <td>{{ $appointment->status()->first()->name }}</td>
            <td>{{ $appointment->event_title }}</td>
            <td>{{ $appointment->start_time }}</td>
            <td>{{ $appointment->end_time_exp }}</td>
            <td></td>
        </tr>
        @endif

        @if($loop->iteration < 1)
            <tr>
                <td colspan="5"><p>Geen nieuwe afspraken beschikbaar.</p></td>
            </tr>
        @endif
    @endforeach
    </tbody>
</table>
@else
    <p>Er zijn momenteel geen nieuwe afspraken die goedkeuring vereisen.</p>
@endif

resources/views/shared/tables/users.blade.php
<table class="table table-sm table-hover">
    <thead>
    <tr>
        <th scope="col" width="50">#</th>
        <th scope="col">Rechten</th>
        <th scope="col">Voornaam</th>
        <th scope="col">Achternaam</th>
        <th scope="col">E-mail</th>
        <th scope="col"  width="50">Actief</th>
    </tr>
    </thead>
    <tbody>
    @foreach($users as $user)
        <tr class='clickable-row' data-href='{{ route('admin.user.detail', $user->id) }}'>
            <td>{{ isset($user->id) ? $user->id : '' }}</td>
            <td>
                   {{ucfirst($user->roles->last()->name)}}
            </td>
            <td>{{ isset($user->first_name) ? ucfirst($user->first_name) : '' }}</td>
            <td>{{ isset($user->last_name) ? ucfirst($user->last_name) : '' }}</td>
            <td>{{ isset($user->email) ? $user->email : '' }}</td>
            <td class="text-center">
                @if(isset($user->is_active) && $user->is_active > 0)
                    <i class="fas fa-fw fa-check"></i>
                @endif
            </td>
        </tr>
    @endforeach
    </tbody>
</table>