routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;

/*
 *** PUBLIC WEBSITE (views):
 */
Route::get('/', 'PublicViewController@showHome')->name('home');
Route::post('/lead', 'Message\LeadController@store')->name('lead.store');

Auth::routes();

Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);

/*
 *** USERS PANEL (views):
 */
Route::prefix('user')->group(function () {
    Route::name('user.')->group(function () {

        Route::prefix('profile')->group(function () {
            Route::get('/', 'UserViewController@profile')->name('profile');

            Route::name('profile.')->group(function () {
                Route::get('edit', 'UserViewController@editProfile')->name('edit');
                Route::get('/password/change', 'UserViewController@showChangePassword')->name('password.change');

                Route::prefix('address')->group(function () {
                    Route::name('address.')->group(function () {
                        Route::get('/create', 'UserViewController@createAddress')->name('new');
                        Route::get('{address}', 'UserViewController@showAddress')->name('detail');
                        Route::get('{address}/edit', 'UserViewController@editAddress')->name('edit');
                    });
                });
            });
        });

        Route::prefix('address')->group(function () {
            Route::name('address.')->group(function () {
                Route::get('{address}', 'UserViewController@showAddress')->name('detail');
                Route::get('{address}/edit', 'UserViewController@editAddress')->name('edit');
            });
        });

        Route::get('appointments', 'UserViewController@appointments')->name('appointments');

        Route::prefix('mailbox')->group(function () {
            Route::get('/', 'UserViewController@showInbox')->name('inbox');

            Route::name('mailbox.')->group(function () {
                Route::get('create', 'UserViewController@createMessage')->name('new');
                Route::get('history', 'UserViewController@showHistory')->name('history');
                Route::get('{message}', 'UserViewController@showMessage')->name('detail');
            });
        });
    });
});

/*
 *** ADMIN PANEL (views):
 */
Route::prefix('admin')->group(function () {

    Route::name('admin.')->group(function () {
        Route::get('/', 'AdminViewController@showDashboard')->name('dashboard');

        Route::prefix('profile')->group(function () {
            Route::get('/', 'AdminViewController@showProfile')->name('profile');

            Route::name('profile.')->group(function () {
                Route::get('edit', 'AdminViewController@editProfile')->name('edit');
                Route::get('/password/change', 'AdminViewController@showChangePassword')->name('password.change');
                Route::get('/password/changed', 'AdminViewController@showChangePassword')->name('password.changed');

                Route::prefix('address')->group(function () {
                    Route::name('address.')->group(function () {
                        Route::get('/create', 'AdminViewController@createAddress')->name('new');
                        Route::get('{address}', 'AdminViewController@showAddress')->name('detail');
                        Route::get('{address}/edit', 'AdminViewController@editAddress')->name('edit');
                    });
                });
            });
        });

        Route::prefix('addresses')->group(function () {
            Route::get('/', 'AdminViewController@showAddresses')->name('addresses');
        });

        Route::prefix('address')->group(function () {
            Route::name('address.')->group(function () {
                Route::get('{address}', 'AdminViewController@showAddress')->name('detail');
                Route::get('{address}/edit', 'AdminViewController@editAddress')->name('edit');
            });
        });



        Route::prefix('mailbox')->group(function () {
            Route::get('/', 'AdminViewController@showInbox')->name('inbox');

            Route::name('mailbox.')->group(function () {
                Route::get('create', 'AdminViewController@createMessage')->name('new');
                Route::get('history', 'AdminViewController@showHistory')->name('history');
                Route::get('{message}', 'AdminViewController@showMessage')->name('detail');
            });
        });

        Route::prefix('appointments')->group(function () {
            Route::get('/', 'AdminViewController@showAppointmentsCalendar')->name('appointments');

            Route::name('appointments.')->group(function () {
                Route::get('pending', 'AdminViewController@showAppointmentsPending')->name('pending');
                Route::get('history', 'AdminViewController@showAppointmentsHistory')->name('history');
            });
        });

        Route::prefix('appointment')->group(function () {
            Route::name('appointment.')->group(function () {
                Route::get('create', 'AdminViewController@createAppointment')->name('new');
                Route::get('{appointment}', 'AdminViewController@showAppointment')->name('detail');
                Route::get('{appointment}/edit', 'AdminViewController@editAppointment')->name('edit');
            });
        });

        Route::prefix('users')->group(function () {
            Route::get('/', 'AdminViewController@showUsers')->name('users');
        });

        Route::prefix('user')->group(function () {
            Route::name('user.')->group(function () {
                Route::get('{user}', 'AdminViewController@showProfile')->name('detail');
                Route::get('{user}/edit', 'AdminViewController@editProfile')->name('edit');
                Route::get('{user}/role/edit', 'AdminViewController@showChangeRole')->name('role.edit');
                Route::get('{user}/address/new', 'AdminViewController@createAddress')->name('address.new');
                Route::get('address/{address}', 'AdminViewController@showAddress')->name('address.detail');
                Route::get('address/{address}/edit', 'AdminViewController@editAddress')->name('address.edit');
            });
        });
    });

});



/*
 *** MODELS RESOURCE CONTROLLERS:
 */
Route::resource('address', 'Address\AddressController')->except('index', 'show' , 'create', 'edit');
Route::resource('message', 'Message\MessageController')->except('index', 'show' , 'create', 'edit');
Route::resource('users', 'User\UsersController')->except('index', 'create', 'show', 'edit', 'store');
Route::resource('appointment', 'Appointment\AppointmentController')->except('index', 'show' , 'create', 'edit');




Route::put('users/{user}/pass', 'User\UsersController@changePassword')->name('users.change.password');
Route::put('users/{user}/role', 'User\UsersController@changeRole')->name('users.change.role');
Route::get('users/{user}', 'User\UsersController@activate')->name('users.activate');
Route::get('/message/{recipient}/unread', 'Message\MessageController@updateIsUnread')->name('message.update.unread');
Route::get('/message/{recipient}/isread', 'Message\MessageController@updateIsRead')->name('message.update.read');
Route::delete('/message/{message}/{recipient}', 'Message\MessageController@destroyRecipient')->name('message.destroy.recipient');

resources/views/shared/forms/address.blade.php
<form method="POST" action="{{ isset($address) ? route('address.update', $address) :  route('address.store') }}">
    @csrf

    @if(isset($address))
        @method('PUT')
    @endif

    <div class="form-group row">
        <label class="col-md-4 col-xl-2 col-form-label text-md-right">{{ __('Adres Type ') }}</label>
        <div class="col-md-6 col-xl-8 form-control-plaintext">
            @if(Request::is('admin/addresses/') || Request::is('admin/addresses') || Request::is('admin/addresses/*'))
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="address_type" id="inlineRadioCommunity" value="Home" {{ isset($address) ? ($address->address_type === 'Home' ?  'checked' : '' ) : (old('address_type') === 'Home' ? 'checked' : '') }} required>
                <label class="form-check-label" for="inlineRadioCommunity">Thuis Adres</label>
            </div>
            @endif
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="address_type" id="inlineRadioCommunity" value="Community" {{ isset($address) ? ($address->address_type === 'Community' ?  'checked' : '' ) : (old('address_type') === 'Community' ? 'checked' : '') }} required>
                <label class="form-check-label" for="inlineRadioCommunity">Gemeendschapshuis</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="address_type" id="inlineRadioEvent" value="Event" {{ isset($address) ? ($address->address_type === 'Event' ?  'checked' : '' ) : (old('address_type') === 'Event' ? 'checked' : '') }} required>
                <label class="form-check-label" for="inlineRadioEvent">Event locatie</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="address_type" id="inlineRadioRestaurant" value="Restaurant" {{ isset($address) ? ($address->address_type === 'Restaurant' ?  'checked' : '' ) : (old('address_type') === 'Restaurant' ? 'checked' : '') }} required>
                <label class="form-check-label" for="inlineRadioRestaurant">Restaurant</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="address_type" id="inlineRadioOther" value="Other" {{ isset($address) ? ($address->address_type === 'Other' ?  'checked' : '' ) : (old('address_type') === 'Other' ? 'checked' : '') }} required>
                <label class="form-check-label" for="inlineRadioOther">Anders</label>
            </div>
        </div>
    </div>

    <div class="form-group row">
        <label for="line_1" class="col-md-4 col-xl-2 col-form-label text-md-right">{{ __('Straat ') }}</label>

        <div class="col-md-6 col-xl-8">
            <input id="line_1" type="text" class="form-control{{ $errors->has('line_1') ? ' is-invalid' : '' }}" name="line_1" value="{{ isset($address) ? $address->line_1 : old('line_1') }}" >

            @if ($errors->has('line_1'))
                <span class="invalid-feedback">
                    <strong>{{ $errors->first('line_1') }}</strong>
                </span>
            @endif
        </div>
    </div>

    <div class="form-group row">
        <label for="line_2" class="col-md-4 col-xl-2  col-form-label text-md-right">{{ __('Huisnummer') }}</label>

        <div class="col-md-6 col-xl-8">
            <input id="line_2" type="text" class="form-control{{ $errors->has('line_2') ? ' is-invalid' : '' }}" name="line_2" value="{{ isset($address) ? $address->line_2 : old('line_2') }}" required>

            @if ($errors->has('line_2'))
                <span class="invalid-feedback">
                    <strong>{{ $errors->first('line_2') }}</strong>
                </span>
            @endif
        </div>
    </div>

    <div class="form-group row">
        <label for="line_3" class="col-md-4 col-xl-2  col-form-label text-md-right">{{ __('Extra Adres gegevens') }}</label>

        <div class="col-md-6 col-xl-8">
            <input id="line_3" type="text" class="form-control{{ $errors->has('line_3') ? ' is-invalid' : '' }}" name="line_3" value="{{ isset($address) ? $address->line_3 : old('line_3') }}">

            @if ($errors->has('line_3'))
                <span class="invalid-feedback">
                    <strong>{{ $errors->first('line_3') }}</strong>
                </span>
            @endif
        </div>
    </div>

    <div class="form-group row">
        <label for="zip_code" class="col-md-4 col-xl-2  col-form-label text-md-right">{{ __('Postcode') }}</label>

        <div class="col-md-6 col-xl-8">
            <input id="zip_code" type="text" class="form-control{{ $errors->has('zip_code') ? ' is-invalid' : '' }}" name="zip_code" value="{{ isset($address) ? $address->zip_code : old('zip_code') }}" required>

            @if ($errors->has('zip_code'))
                <span class="invalid-feedback">
                    <strong>{{ $errors->first('zip_code') }}</strong>
                </span>
            @endif
        </div>
    </div>

    <div class="form-group row">
        <label for="city" class="col-md-4 col-xl-2  col-form-label text-md-right">{{ __('Stad') }}</label>

        <div class="col-md-6 col-xl-8">
            <input id="city" type="text" class="form-control{{ $errors->has('city') ? ' is-invalid' : '' }}" name="city" value="{{ isset($address) ? $address->city : old('city') }}" required>

            @if ($errors->has('zip_code'))
                <span class="invalid-feedback">
                    <strong>{{ $errors->first('zip_code') }}</strong>
                </span>
            @endif
        </div>
    </div>

    <div class="form-group row">
        <label for="country" class="col-md-4 col-xl-2  col-form-label text-md-right">{{ __('Land') }}</label>

        <div class="col-md-6 col-xl-8">

            <select id="country" class="form-control" name="country">
                @foreach( $countries as $country)
                    <option value="{{ $country->id }}" {{ $country->id !==  old('country') ? (isset($address) && $address->countries->first()->id === $country->id ? 'selected' : '') : 'selected' }}>{{ $country->name }}</option>
                @endforeach
            </select>

            @if ($errors->has('country'))
                <span class="invalid-feedback">
                    <strong>{{ $errors->first('country') }}</strong>
                </span>
            @endif
        </div>
    </div>

    <div class="form-group row">
        <label for="misc" class="col-md-4 col-xl-2 col-form-label text-md-right">{{ __('Extra Informatie') }}</label>

        <div class="col-md-6 col-xl-8">
            <textarea name="misc" id="misc" cols="30" rows="10" class="form-control{{ $errors->has('misc') ? ' is-invalid' : '' }}">{{ isset($address) ? $address->misc : old('misc') }}</textarea>


            @if ($errors->has('misc'))
                <span class="invalid-feedback">
                    <strong>{{ $errors->first('misc') }}</strong>
                </span>
            @endif
        </div>
    </div>

    <div class="form-group row mb-0">
        <div class="col-md-6 col-xl-8 offset-md-4 offset-xl-2">
            <div class="d-flex justify-content-between no-gutters">

                    @if(Request::is('admin/user/') || Request::is('admin/user') || Request::is('admin/user/*'))
                        <a href="{{ route('admin.user.detail', $user) }}" class="btn btn-outline-dark">Ga Terug</a>
                    @elseif(Request::is('admin/profile/') || Request::is('admin/prof') || Request::is('admin/user/*'))
                        <a href="{{ route('admin.profile') }}" class="btn btn-outline-dark">Ga Terug</a>
                    @else
                        <a href="{{ route('user.profile') }}" class="btn btn-outline-dark">Ga Terug</a>
                    @endif

                <button type="submit" class="btn btn-outline-dark">
                    {{ __('Versturen') }}
                </button>
            </div>
        </div>
    </div>
</form>

resources/views/shared/forms/change_password.blade.php
<form class="form-horizontal" method="POST" action="{{ route('users.change.password', $user) }}">
    @csrf
    @method('PUT')
    <div class="form-group row {{ $errors->has('current-password') ? ' has-error' : '' }}">
        <label for="new-password" class="col-md-4 col-xl-2 col-form-label text-md-right">Huidige Wachtwoord</label>

        <div class="col-md-6 col-xl-8">
            <input id="current-password" type="password" class="form-control" name="current-password" required>

            @if ($errors->has('current-password'))
                <span class="help-block">
                    <strong>{{ $errors->first('current-password') }}</strong>
                </span>
            @endif
        </div>
    </div>


    <div class="form-group row {{ $errors->has('new-password') ? ' has-error' : '' }}">
        <label for="new-password" class="col-md-4 col-xl-2 col-form-label text-md-right">Nieuwe Wachtwoord</label>

        <div class="col-md-6 col-xl-8">
            <input id="new-password" type="password" class="form-control" name="new-password" required>

            @if ($errors->has('new-password'))
            <span class="help-block">
                                        <strong>{{ $errors->first('new-password') }}</strong>
                                    </span>
            @endif
        </div>
    </div>

    <div class="form-group row">
        <label for="new-password-confirm" class="col-md-4 col-xl-2 col-form-label text-md-right">Bevestig Nieuwe Wachtwoord</label>

        <div class="col-md-6 col-xl-8">
            <input id="new-password-confirm" type="password" class="form-control" name="new-password_confirmation" required>
        </div>
    </div>

    <div class="form-group row mb-0">
        <div class="col-md-6 col-xl-8 offset-md-4 offset-xl-2">
            <div class="d-flex justify-content-between no-gutters">

                @if(Request::is('admin/user/') || Request::is('admin/user') || Request::is('admin/user/*'))
                    <a href="{{ route('admin.user.detail', $user) }}" class="btn btn-outline-dark">Ga Terug</a>
                @elseif(Request::is('admin/profile/') || Request::is('admin/profile') || Request::is('admin/profile/*'))
                    <a href="{{ route('admin.profile.edit') }}" class="btn btn-outline-dark">Ga Terug</a>
                @else
                    <a href="{{ route('user.profile.edit') }}" class="btn btn-outline-dark">Ga Terug</a>
                @endif

                <button type="submit" class="btn btn-outline-dark">
                    {{ __('Versturen') }}
                </button>
            </div>
        </div>
    </div>
</form>

resources/views/shared/forms/edit_home_address.blade.php
<form method="POST" action="{{ route('address.update' , $homeAddress) }}">
    @csrf
    @method('PUT')
    <div class="form-group row">
        <label for="line_1" class="col-md-4 col-xl-2 col-form-label text-md-right">{{ __('Adres') }}</label>

        <div class="col-md-6 col-xl-8">
            <input id="line_1" type="text" class="form-control{{ $errors->has('line_1') ? ' is-invalid' : '' }}" name="line_1" value="{{ old('line_1') != null ? old('line_1') : (isset($homeAddress->line_1) ? $homeAddress->line_1 : '') }}" required>

            @if ($errors->has('line_1'))
                <span class="invalid-feedback">
                    <strong>{{ $errors->first('line_1') }}</strong>
                </span>
            @endif
        </div>
    </div>

    <div class="form-group row">
        <label for="line_2" class="col-md-4 col-xl-2  col-form-label text-md-right">{{ __('Huisnummer') }}</label>

        <div class="col-md-6 col-xl-8">
            <input id="line_2" type="text" class="form-control{{ $errors->has('line_2') ? ' is-invalid' : '' }}" name="line_2" value="{{ old('line_2') != null ? old('line_2') : (isset($homeAddress->line_2) ? $homeAddress->line_2 : '') }}" required>

            @if ($errors->has('line_2'))
                <span class="invalid-feedback">
                    <strong>{{ $errors->first('line_2') }}</strong>
                </span>
            @endif
        </div>
    </div>

    <div class="form-group row">
        <label for="zip_code" class="col-md-4 col-xl-2  col-form-label text-md-right">{{ __('Postcode') }}</label>

        <div class="col-md-6 col-xl-8">
            <input id="zip_code" type="text" class="form-control{{ $errors->has('zip_code') ? ' is-invalid' : '' }}" name="zip_code" value="{{ old('zip_code') != null ? old('zip_code') : (isset($homeAddress->zip_code) ? $homeAddress->zip_code : '') }}" required>

            @if ($errors->has('zip_code'))
                <span class="invalid-feedback">
                    <strong>{{ $errors->first('zip_code') }}</strong>
                </span>
            @endif
        </div>
    </div>

    <div class="form-group row">
        <label for="city" class="col-md-4 col-xl-2  col-form-label text-md-right">{{ __('Stad') }}</label>

        <div class="col-md-6 col-xl-8">
            <input id="city" type="text" class="form-control{{ $errors->has('city') ? ' is-invalid' : '' }}" name="city" value="{{ old('city') != null ? old('city') : (isset($homeAddress->city) ? $homeAddress->city : '') }}" required>

            @if ($errors->has('zip_code'))
                <span class="invalid-feedback">
                    <strong>{{ $errors->first('zip_code') }}</strong>
                </span>
            @endif
        </div>
    </div>

    <div class="form-group row">
        <label for="country" class="col-md-4 col-xl-2  col-form-label text-md-right">{{ __('Land') }}</label>

        <div class="col-md-6 col-xl-8">

            <select id="country" class="form-control" name="country">
                @foreach( $countries as $country)
                <option value="{{ $country->id }}" {{ $country->id === $homeAddress->countries->first()->id ? 'selected' : '' }}>{{ $country->name }}</option>
                @endforeach
            </select>

            @if ($errors->has('country'))
                <span class="invalid-feedback">
                    <strong>{{ $errors->first('country') }}</strong>
                </span>
            @endif
        </div>
    </div>


    <div class="form-group row mb-0 pt-3">
        <div class="col-md-6 col-xl-8 offset-md-4 offset-xl-2">
            <div class="d-flex justify-content-between no-gutters">
                @if(Request::is('admin/profile/') || Request::is('admin/profile') || Request::is('admin/profile/*'))
                    <a href="{{ route('admin.profile') }}" class="btn btn-outline-dark">Ga Terug</a>
                @elseif(Request::is('admin/user/') || Request::is('admin/user') || Request::is('admin/user/*'))
                    <a href="{{ route('admin.user.detail', $user) }}" class="btn btn-outline-dark">Ga Terug</a>
                @elseif(Request::is('user/profile/') || Request::is('user/profile') || Request::is('user/profile/*'))
                    <a href="{{ route('user.profile') }}" class="btn btn-outline-dark">Ga Terug</a>
                @endif

                <button type="submit" class="btn btn-outline-dark">
                    {{ __('Versturen') }}
                </button>
            </div>
        </div>
    </div>
</form>

resources/views/shared/forms/edit_profile.blade.php
    <form method="POST" action="{{ route('users.update', $user) }}" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="form-group row">
            <label for="first_name" class="col-md-4 col-xl-2  col-form-label text-md-right">{{ __('Voornaam') }}</label>

            <div class="col-md-6 col-xl-8">
                <input id="first_name" type="text" class="form-control{{ $errors->has('first_name') ? ' is-invalid' : '' }}" name="first_name" value="{{ old('first_name') != null ? old('first_name') : (isset($user->first_name) ? $user->first_name : '') }}" required>

                @if ($errors->has('first_name'))
                    <span class="invalid-feedback">
                        <strong>{{ $errors->first('first_name') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <div class="form-group row">
            <label for="last_name" class="col-md-4 col-xl-2 col-form-label text-md-right">{{ __('Achternaam') }}</label>

            <div class="col-md-6 col-xl-8">
                <input id="last_name" type="text" class="form-control{{ $errors->has('last_name') ? ' is-invalid' : '' }}" name="last_name" value="{{ old('last_name') != null ? old('last_name') : (isset($user->last_name) ? $user->last_name : '') }}" required>

                @if ($errors->has('last_name'))
                    <span class="invalid-feedback">
                        <strong>{{ $errors->first('last_name') }}</strong>
                    </span>
                @endif
            </div>
        </div>


        <div class="form-group row">
            <label class="col-md-4 col-xl-2 col-form-label text-md-right">{{ __('Wachtwoord') }}</label>

            <div class="col-md-6 col-xl-8">
                <a href="password/change" class="form-control-plaintext">Change Password</a>
            </div>
        </div>

        <div class="form-group row">
            <label for="avatar" class="col-md-4 col-xl-2  col-form-label text-md-right">{{ __('Avatar Aanpassen') }}</label>

            <div class="col-md-6 col-xl-8">
                <div class="row no-gutters">
                    <div class="col-sm-12 col-md-auto pr-2 pb-2">
                        @if(isset($user) && $user->avatar !== null)
                            <img src="{{ asset('storage/avatar/'.$user->avatar->filepath) }}" alt="" class="img-fluid" width="150">
                        @else
                            <img src="/img/Team-member.png" alt="" class="img-fluid" width="150">
                        @endif
                    </div>
                    <div class="col">
                        <input id="avatar" type="file" class="form-control{{ $errors->has('avatar') ? ' is-invalid' : '' }}" name="avatar" value="{{ old('avatar') }}">
                    </div>
                </div>


                @if ($errors->has('avatar'))
                    <span class="invalid-feedback">
                        <strong>{{ $errors->first('avatar') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <div class="form-group row mb-0 mt-3">
            <div class="col-md-6 col-xl-8 offset-md-4 offset-xl-2 text-right">
                <button type="submit" class="btn btn-outline-dark">
                    {{ __('Versturen') }}
                </button>
            </div>
        </div>
    </form>

resources/views/shared/forms/message.blade.php
<form method="POST" action="{{ route('message.store') }}">
    @csrf

    @if(Request::is('admin/mailbox/') || Request::is('admin/mailbox') || Request::is('admin/mailbox/*'))
    <div class="form-group row">
        <label for="to" class="col-md-4 col-xl-2  col-form-label text-md-right">{{ __('Naar') }} :</label>

        <div class="col-md-6 col-xl-8">
            <input id="to" list="users_full_name" class="form-control{{ $errors->has('to') ? ' is-invalid' : '' }}" name="full_name" value="{{ old('to') }}">

            @if ($errors->has('to'))
                <span class="invalid-feedback">
                    <strong>{{ $errors->first('to') }}</strong>
                </span>
            @endif

            <datalist id="users_full_name">
                @foreach($users as $user)
                    @if($user->id !== Auth::user()->id)
                        <option value="{{ $user->full_name }}">
                    @endif
                @endforeach
            </datalist>
        </div>
    </div>
    @endif

    <div class="form-group row">
        <label for="subject" class="col-md-4 col-xl-2  col-form-label text-md-right">{{ __('Onderwerp') }} :</label>

        <div class="col-md-6 col-xl-8">
            <input id="subject" type="text" class="form-control{{ $errors->has('subject') ? ' is-invalid' : '' }}" name="subject" value="{{ old('subject') }}">

            @if ($errors->has('subject'))
                <span class="invalid-feedback">
                    <strong>{{ $errors->first('subject') }}</strong>
                </span>
            @endif
        </div>
    </div>

    <div class="form-group row">
        <label for="message_body" class="col-md-4 col-xl-2  col-form-label text-md-right">{{ __('Bericht') }} :</label>

        <div class="col-md-6 col-xl-8">
            <textarea name="message_body" id="message_body" cols="30" rows="10" class="form-control{{ $errors->has('message_body') ? ' is-invalid' : '' }}">{{ old('message_body') }}</textarea>

            @if ($errors->has('message_body'))
                <span class="invalid-feedback">
                    <strong>{{ $errors->first('message_body') }}</strong>
                </span>
            @endif
        </div>
    </div>

    <div class="form-group row mb-0">
        <div class="col-md-6 col-xl-8 offset-md-4 offset-xl-2">
            <div class="d-flex justify-content-between no-gutters">
                @if(Request::is('admin/') || Request::is('admin') || Request::is('admin/*'))
                    <a href="{{ route('admin.inbox') }}" class="btn btn-outline-dark">Ga Terug</a>
                @elseif(Request::is('user/') || Request::is('user') || Request::is('user/*'))
                    <a href="{{ route('user.inbox') }}" class="btn btn-outline-dark">Ga Terug</a>
                @endif

                <button type="submit" class="btn btn-outline-dark">
                    {{ __('Versturen') }}
                </button>
            </div>
        </div>
    </div>
</form>

resources/views/shared/forms/roles.blade.php
<form method="POST" action="{{ route('users.change.role', $user) }}">
    @csrf
    @method('PUT')
    <div class="form-group row">
        <label for="role" class="col-md-4 col-xl-2  col-form-label text-md-right">{{ __('Role') }} :</label>

        <div class="col-md-6 col-xl-8">
            <select class="form-control{{ $errors->has('role') ? ' is-invalid' : '' }}" id="role" name="role">
                @foreach($roles as $role)
                    <option value="{{$role->id}}" @if($user->roles->last()->name === $role->name) selected @endif> {{ucfirst($role->name)}}</option>
                @endforeach
            </select>
            @if ($errors->has('role'))
                <span class="invalid-feedback">
                        <strong>{{ $errors->first('role') }}</strong>
                    </span>
            @endif
        </div>
    </div>

    <div class="form-group row mb-0 pt-3">
        <div class="col-md-6 col-xl-8 offset-md-4 offset-xl-2">
            <div class="d-flex justify-content-between no-gutters">

                <a href="{{ route('admin.user.detail', $user) }}" class="btn btn-outline-dark">Ga Terug</a>

                <button type="submit" class="btn btn-outline-dark">
                    {{ __('Versturen') }}
                </button>
            </div>
        </div>
    </div>
</form>