routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;

/*
 *** PUBLIC WEBSITE (views):
 */
Route::get('/', 'PublicViewController@showHome')->name('home');
Route::post('/lead', 'Message\LeadController@store')->name('lead.store');

Auth::routes();

Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);

/*
 *** USERS PANEL (views):
 */
Route::prefix('user')->group(function () {
    Route::name('user.')->group(function () {

        Route::prefix('profile')->group(function () {
            Route::get('/', 'UserViewController@profile')->name('profile');

            Route::name('profile.')->group(function () {
                Route::get('edit', 'UserViewController@editProfile')->name('edit');
                Route::get('/password/change', 'UserViewController@showChangePassword')->name('password.change');

                Route::prefix('address')->group(function () {
                    Route::name('address.')->group(function () {
                        Route::get('/create', 'UserViewController@createAddress')->name('new');
                        Route::get('{address}', 'UserViewController@showAddress')->name('detail');
                        Route::get('{address}/edit', 'UserViewController@editAddress')->name('edit');
                    });
                });
            });
        });

        Route::prefix('address')->group(function () {
            Route::name('address.')->group(function () {
                Route::get('{address}', 'UserViewController@showAddress')->name('detail');
                Route::get('{address}/edit', 'UserViewController@editAddress')->name('edit');
            });
        });

        Route::get('appointments', 'UserViewController@appointments')->name('appointments');

        Route::prefix('mailbox')->group(function () {
            Route::get('/', 'UserViewController@showInbox')->name('inbox');

            Route::name('mailbox.')->group(function () {
                Route::get('create', 'UserViewController@createMessage')->name('new');
                Route::get('history', 'UserViewController@showHistory')->name('history');
                Route::get('{message}', 'UserViewController@showMessage')->name('detail');
            });
        });
    });
});

/*
 *** ADMIN PANEL (views):
 */
Route::prefix('admin')->group(function () {

    Route::name('admin.')->group(function () {
        Route::get('/', 'AdminViewController@showDashboard')->name('dashboard');

        Route::prefix('profile')->group(function () {
            Route::get('/', 'AdminViewController@showProfile')->name('profile');

            Route::name('profile.')->group(function () {
                Route::get('edit', 'AdminViewController@editProfile')->name('edit');
                Route::get('/password/change', 'AdminViewController@showChangePassword')->name('password.change');
                Route::get('/password/changed', 'AdminViewController@showChangePassword')->name('password.changed');

                Route::prefix('address')->group(function () {
                    Route::name('address.')->group(function () {
                        Route::get('/create', 'AdminViewController@createAddress')->name('new');
                        Route::get('{address}', 'AdminViewController@showAddress')->name('detail');
                        Route::get('{address}/edit', 'AdminViewController@editAddress')->name('edit');
                    });
                });
            });
        });

        Route::prefix('addresses')->group(function () {
            Route::get('/', 'AdminViewController@showAddresses')->name('addresses');
        });

        Route::prefix('address')->group(function () {
            Route::name('address.')->group(function () {
                Route::get('{address}', 'AdminViewController@showAddress')->name('detail');
                Route::get('{address}/edit', 'AdminViewController@editAddress')->name('edit');
            });
        });



        Route::prefix('mailbox')->group(function () {
            Route::get('/', 'AdminViewController@showInbox')->name('inbox');

            Route::name('mailbox.')->group(function () {
                Route::get('create', 'AdminViewController@createMessage')->name('new');
                Route::get('history', 'AdminViewController@showHistory')->name('history');
                Route::get('{message}', 'AdminViewController@showMessage')->name('detail');
            });
        });

        Route::prefix('appointments')->group(function () {
            Route::get('/', 'AdminViewController@showAppointmentsCalendar')->name('appointments');

            Route::name('appointments.')->group(function () {
                Route::get('pending', 'AdminViewController@showAppointmentsPending')->name('pending');
                Route::get('history', 'AdminViewController@showAppointmentsHistory')->name('history');
            });
        });

        Route::prefix('appointment')->group(function () {
            Route::name('appointment.')->group(function () {
                Route::get('create', 'AdminViewController@createAppointment')->name('new');
                Route::get('{appointment}', 'AdminViewController@showAppointment')->name('detail');
                Route::get('{appointment}/edit', 'AdminViewController@editAppointment')->name('edit');
            });
        });

        Route::prefix('users')->group(function () {
            Route::get('/', 'AdminViewController@showUsers')->name('users');
        });

        Route::prefix('user')->group(function () {
            Route::name('user.')->group(function () {
                Route::get('{user}', 'AdminViewController@showProfile')->name('detail');
                Route::get('{user}/edit', 'AdminViewController@editProfile')->name('edit');
                Route::get('{user}/role/edit', 'AdminViewController@showChangeRole')->name('role.edit');
                Route::get('{user}/address/new', 'AdminViewController@createAddress')->name('address.new');
                Route::get('address/{address}', 'AdminViewController@showAddress')->name('address.detail');
                Route::get('address/{address}/edit', 'AdminViewController@editAddress')->name('address.edit');
            });
        });
    });

});



/*
 *** MODELS RESOURCE CONTROLLERS:
 */
Route::resource('address', 'Address\AddressController')->except('index', 'show' , 'create', 'edit');
Route::resource('message', 'Message\MessageController')->except('index', 'show' , 'create', 'edit');
Route::resource('users', 'User\UsersController')->except('index', 'create', 'show', 'edit', 'store');
Route::resource('appointment', 'Appointment\AppointmentController')->except('index', 'show' , 'create', 'edit');




Route::put('users/{user}/pass', 'User\UsersController@changePassword')->name('users.change.password');
Route::put('users/{user}/role', 'User\UsersController@changeRole')->name('users.change.role');
Route::get('users/{user}', 'User\UsersController@activate')->name('users.activate');
Route::get('/message/{recipient}/unread', 'Message\MessageController@updateIsUnread')->name('message.update.unread');
Route::get('/message/{recipient}/isread', 'Message\MessageController@updateIsRead')->name('message.update.read');
Route::delete('/message/{message}/{recipient}', 'Message\MessageController@destroyRecipient')->name('message.destroy.recipient');

resources/views/admin_panel/profile/all.blade.php
@extends('layouts.admin')

@section('breadcrumb')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}" >Admin Panel</a></li>
            <li class="breadcrumb-item active" aria-current="page">Gebruikers</li>
        </ol>
    </nav>
@endsection

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex justify-content-between">
                        <h2 class="h4"><i class="fas fa-fw fa-users"></i> Alle Geregistreerde Gebruikers</h2>
                    </div>
                </div>
                <div class="card-body">
                @include('shared.tables.users')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin_panel/profile/change_password.blade.php
@extends('layouts.admin')

@section('breadcrumb')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Admin panel</a></li>
            @if(Request::is('admin/user/') || Request::is('admin/user') || Request::is('admin/user/*'))
                <li class="breadcrumb-item"><a href="{{ route('admin.users') }}" >Gebruikers</a></li>
                <li class="breadcrumb-item"><a href="{{ route('admin.user.detail' , $user) }}" >Profiel</a></li>
                <li class="breadcrumb-item"><a href="{{ route('admin.user.edit') }}">Aanpassen</a></li>
            @else
                <li class="breadcrumb-item"><a href="{{ route('admin.profile') }}">Profiel</a></li>
            @endif
            <li class="breadcrumb-item active" aria-current="page">Wachtwoord Aanpassen</li>
        </ol>
    </nav>
@endsection

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="card card-header">
                <div class="d-flex justify-content-between">
                    <h1 class="h4">Wachtwoord Aanpassen</h1>
                </div>
            </div>
        </div>

        <div class="col-sm-12">
            <div class="card card-body">
                @include('shared.forms.change_password')
            </div>
        </div>
    </div>
@endsection

resources/views/admin_panel/profile/details.blade.php
@extends('layouts.admin')

@section('breadcrumb')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}" >Admin panel</a></li>
            @if(Request::is('admin/profile/') || Request::is('admin/profile') || Request::is('admin/profile/*'))
                <li class="breadcrumb-item active" aria-current="page">Profiel</li>
            @elseif(Request::is('admin/user/') || Request::is('admin/user') || Request::is('admin/user/*'))
                <li class="breadcrumb-item"><a href="{{ route('admin.users') }}" >Gebruikers</a></li>
                <li class="breadcrumb-item active" aria-current="page">Profiel</li>
            @endif
        </ol>
    </nav>
@endsection

@section('content')
    <div class="row no-gutters">
        <div class="col-sm-12">
            <div class="card card-header">
                <div class="d-flex justify-content-between">
                    <h1 class="h4">Profiel</h1>

                    @if(Request::is('admin/user/') || Request::is('admin/user') || Request::is('admin/user/*'))
                        <form action="{{route('users.destroy' , $user)}}" method="post" class="btn-group-sm">
                            @csrf
                            @method('DELETE')
                            @if(Auth::user()->hasRole('admin'))
                                <a href="{{route('admin.user.role.edit', $user)}}" class="btn btn-sm btn-outline-dark">Rechten aanpassen</a>
                            @endif
                            <a href="{{route('admin.user.edit', $user)}}" class="btn btn-sm btn-outline-dark">Aanpassen</a>

                            @if(Request::is('admin/user/') || Request::is('admin/user') || Request::is('admin/user/*'))
                                @if($user->is_active !== 0)
                                    <button type="submit" class="btn btn-sm btn-outline-danger">Deactiveren</button>
                                @else
                                    <a href="{{route('users.activate', $user)}}" class="btn btn-sm btn-outline-dark">Activeren</a>
                                @endif
                            @endif
                        </form>
                    @else
                        <div class="btn-group-sm">
                            <a href="{{route('admin.profile.edit')}}" class="btn btn-sm btn-outline-dark">Aanpassen</a>
                        </div>
                    @endif
                </div>
            </div>
        </div>

        <div class="card avatar">
            @if(isset($user) && $user->avatar !== null)
                <img src="{{ asset('storage/avatar/'.$user->avatar->filepath) }}" alt="" class="img-fluid">
            @else
                <img src="/img/Team-member.png" alt="" class="img-fluid">
            @endif
        </div>

        <div class="col card">
            <div class="card-body">
                <h2 class="h4"><i class="fas fa-fw fa-user"></i> Persoonlijke Gegevens</h2>
                <ul class="list-unstyled display-list">
                    <li>
                        <i class="far fa-fw fa-user"></i>
                        <span class="label medium">Volledige naam</span> :
                        {{isset($user->full_name)? $user->full_name : ''}}
                    </li>
                    <li>
                        <i class="far fa-fw fa-user"></i>
                        <span class="label medium">Voornaam</span> :
                        {{isset($user->first_name)? $user->first_name : ''}}
                    </li>
                    <li>
                        <i class="far fa-fw fa-user"></i>
                        <span class="label medium">Achternaam</span> :
                        {{isset($user->last_name)? $user->last_name : ''}}
                    </li>
                    <li>
                        <i class="far fa-fw fa-envelope"></i>
                        <span class="label medium">Email</span> :
                        {{isset($user->email)? $user->email : ''}}
                    </li>
                    <li>
                        <i class="far fa-fw fa-calendar-alt"></i>
                        <span class="label medium">Laatste login</span> :
                        {{ isset($user->last_login) ? $user->last_login->format('H:i d/m/Y') : '' }}
                    </li>
                </ul>
            </div>
        </div>

        <div class="col-sm-12 col-xl-3 card">
            <div class="card-body">
                <h2 class="h4"><i class="fas fa-fw fa-home"></i> Adressen</h2>
                @include('shared.panels.home_address_details')
            </div>
        </div>
    </div>



    <div class="row mt-3">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h2 class="h4"><i class="fas fa-fw fa-home"></i> Statistieken</h2>
                </div>
                <div class="card-body">
                    @include('shared.panels.statistics_details')
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex justify-content-between">
                        <h2 class="h4"><i class="far fa-fw fa-calendar-alt"></i> Aanverwante adressen</h2>

                        <div class="btn-group-sm">
                        @if(Request::is('admin/profile/') || Request::is('admin/profile') || Request::is('admin/profile/*'))
                            <a href="{{ route('admin.profile.address.new') }}" class="btn btn-sm btn-outline-dark">Nieuw Adres</a>
                        @elseif(Request::is('admin/user/') || Request::is('admin/user') || Request::is('admin/user/*'))
                            <a href="{{ route('admin.user.address.new', $user) }}" class="btn btn-sm btn-outline-dark">Nieuw Adres</a>
                        @endif
                        </div>
                    </div>

                </div>
                <div class="card-body table-responsive">
                    @include('shared.tables.addresses_widget')
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h2 class="h4"><i class="far fa-fw fa-calendar-alt"></i> Boekingen</h2>
                </div>
                <div class="card-body table-responsive">
                    @include('shared.tables.appointments_users')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin_panel/profile/form.blade.php
@extends('layouts.admin')

@section('breadcrumb')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Admin panel</a></li>
        @if(Request::is('admin/user/') || Request::is('admin/user') || Request::is('admin/user/*'))
            <li class="breadcrumb-item"><a href="{{ route('admin.users') }}" >Gebruikers</a></li>
            <li class="breadcrumb-item"><a href="{{ route('admin.user.detail' , $user) }}" >Profiel</a></li>
        @else
            <li class="breadcrumb-item"><a href="{{ route('admin.profile') }}">Profiel</a></li>

        @endif
            <li class="breadcrumb-item active" aria-current="page">Aanpassen</li>
        </ol>
    </nav>
@endsection

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="card card-header">
                <div class="d-flex justify-content-between">
                    <h1 class="h4">Account Gegevens</h1>
                </div>
            </div>
        </div>

        <div class="col-sm-12">
            <div class="card card-body">
                @include('shared.forms.edit_profile')
            </div>
        </div>

        <div class="col-sm-12 mt-3">
            <div class="card card-header">
                <div class="d-flex justify-content-between">
                    <h1 class="h4">Adres Gegevens</h1>
                </div>
            </div>
        </div>

        <div class="col-sm-12">
            <div class="card card-body">
                @include('shared.forms.edit_home_address')
            </div>
        </div>
        @if(!Request::is('admin/profile/') || !Request::is('admin/profile') || !Request::is('admin/profile/*'))
            <div class="col-sm-12 mt-3">
                <div class="card card-header">
                    <div class="d-flex justify-content-between">
                        <h1 class="h4">Delete Mijn Account</h1>
                    </div>
                </div>
            </div>

            <div class="col-sm-12">
                <div class="card card-body">
                    <div class="row">
                        <div class="col-sm-12 col-md-8 offset-md-2">
                            <p class="text-center">
                                Als u wilt dat uw account verwijderd word, wat inhoud: dat u word uitgelogt en niet meer kan inloggen met dit account
                                en uw gegevens worden verwijdert, klik dan op "Verwijderen".
                            </p>

                            <div class="text-right">
                                <form action="{{route('users.destroy' , $user)}}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-outline-danger">
                                        {{ __('Verwijderen') }}
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        @endif
    </div>
@endsection

resources/views/admin_panel/profile/role.blade.php
@extends('layouts.admin')

@section('breadcrumb')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Admin panel</a></li>
            @if(Request::is('admin/user/') || Request::is('admin/user') || Request::is('admin/user/*'))
                <li class="breadcrumb-item"><a href="{{ route('admin.users') }}" >Gebruikers</a></li>
                <li class="breadcrumb-item"><a href="{{ route('admin.user.detail' , $user) }}" >Profiel</a></li>
            @else
                <li class="breadcrumb-item"><a href="{{ route('admin.profile') }}">Profiel</a></li>
            @endif
            <li class="breadcrumb-item active" aria-current="page">Rechten aanpassen</li>
        </ol>
    </nav>
@endsection

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="card card-header">
                <div class="d-flex justify-content-between">
                    <h1 class="h4">Rechten aanpassen</h1>
                </div>
            </div>
        </div>

        <div class="col-sm-12">
            <div class="card card-body">
                @include('shared.forms.roles')
            </div>
        </div>
    </div>
@endsection